// Auto-generated from WOKI_WOKI_FoodCost_UPDATED.xlsx
// Update by re-running the extraction script when foodcost changes

export interface FoodcostProduct {
  name: string
  category: string
  price_per_kg: number | null
  type: "ingredient" | "dish"
}

export const FOODCOST_PRODUCTS: FoodcostProduct[] = [
  { name: "Makaron Udon", category: "Makarony", price_per_kg: 14.0, type: "ingredient" },
  { name: "Makaron Soba", category: "Makarony", price_per_kg: 12.77, type: "ingredient" },
  { name: "Makaron Sojowy", category: "Makarony", price_per_kg: 5.53, type: "ingredient" },
  { name: "Makaron Ryżowy", category: "Makarony", price_per_kg: 21.33, type: "ingredient" },
  { name: "Makaron Ramen", category: "Makarony", price_per_kg: 13.64, type: "ingredient" },
  { name: "Ryż", category: "Makarony", price_per_kg: null, type: "ingredient" },
  { name: "Pierś z Kurczaka", category: "Mięso", price_per_kg: 23.32, type: "ingredient" },
  { name: "Udko z Kury", category: "Mięso", price_per_kg: 9.61, type: "ingredient" },
  { name: "Pierś z Kaczki", category: "Mięso", price_per_kg: 52.37, type: "ingredient" },
  { name: "Rostbef Wołowy", category: "Mięso", price_per_kg: 58.59, type: "ingredient" },
  { name: "Polędwiczka Wieprzowa", category: "Mięso", price_per_kg: 31.55, type: "ingredient" },
  { name: "Łosoś", category: "Ryby", price_per_kg: 73.22, type: "ingredient" },
  { name: "Krewetka 16/20", category: "Ryby", price_per_kg: null, type: "ingredient" },
  { name: "Marchewka", category: "Warzywa", price_per_kg: 3.25, type: "ingredient" },
  { name: "Cebula Czerwona", category: "Warzywa", price_per_kg: 6.29, type: "ingredient" },
  { name: "Por", category: "Warzywa", price_per_kg: 13.14, type: "ingredient" },
  { name: "Pieczarka", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Papryka", category: "Warzywa", price_per_kg: 31.03, type: "ingredient" },
  { name: "Mango", category: "Warzywa", price_per_kg: 13.04, type: "ingredient" },
  { name: "Cukinia", category: "Warzywa", price_per_kg: 14.77, type: "ingredient" },
  { name: "Szpinak Baby", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Kolendra", category: "Warzywa", price_per_kg: 12.56, type: "ingredient" },
  { name: "Cebulka Dymka", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Limonka", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Imbir", category: "Warzywa", price_per_kg: 25.06, type: "ingredient" },
  { name: "Czosnek", category: "Warzywa", price_per_kg: 22.06, type: "ingredient" },
  { name: "Papryczka Chilli", category: "Warzywa", price_per_kg: 38.83, type: "ingredient" },
  { name: "Pędy Bambusa", category: "Warzywa", price_per_kg: 20.4, type: "ingredient" },
  { name: "Mini Kukurydza", category: "Warzywa", price_per_kg: 5.24, type: "ingredient" },
  { name: "Mini Brokuł", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Fasola Cięta", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Kiełki F.Mung", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Kiełki Lucerny", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Pak-Choi", category: "Warzywa", price_per_kg: 30.53, type: "ingredient" },
  { name: "Ananas Puszka", category: "Warzywa", price_per_kg: 19.42, type: "ingredient" },
  { name: "Jabłko", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Banany", category: "Warzywa", price_per_kg: null, type: "ingredient" },
  { name: "Edamame", category: "Warzywa", price_per_kg: 23.98, type: "ingredient" },
  { name: "Kikkoman", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Mirin", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Suehiro", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Sriracha Zielona", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Sos Rybny", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Pasta Tom-Ka", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Pasta Curry Zielona", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Pasta Miso Jasna", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Pasta Gochujang", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Gochugaru", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Oshinko", category: "Azjatyckie", price_per_kg: 21.6, type: "ingredient" },
  { name: "Tofu", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Tahini", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Olej Sezamowy", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Mleko Kokosowe", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Tempura", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Kim-Chi (gotowe)", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Matcha", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Dashi", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Wakame", category: "Azjatyckie", price_per_kg: null, type: "ingredient" },
  { name: "Sezam Biały", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Sezam Czarny", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Orzeszki Ziemne", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Orzech Nerkowca", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Słonecznik Łuskany", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Płatki Migdałów", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Pestki Dyni", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Tymianek", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Rozmaryn", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Mięta", category: "Przyprawy", price_per_kg: null, type: "ingredient" },
  { name: "Sok Pomarańczowy", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Olej", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Cukier", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Jajka K1", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Mąka", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Sól", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Woda Niegazowana", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Pulpa Mango", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Magia (Ajinomoto)", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Worki Wakum", category: "Inne", price_per_kg: null, type: "ingredient" },
  { name: "Box", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Torba Papierowa", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Pałeczki", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Serwetka Box", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Widelczyk", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Łyżki", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Miso opakowanie", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "Zupa opakowanie", category: "Opakowania", price_per_kg: null, type: "ingredient" },
  { name: "TOKIO", category: "DANIA", price_per_kg: 47.0, type: "dish" },
  { name: "YOKOHAMA", category: "DANIA", price_per_kg: 50.0, type: "dish" },
  { name: "OSAKA", category: "DANIA", price_per_kg: 42.0, type: "dish" },
  { name: "KOBE", category: "DANIA", price_per_kg: 46.0, type: "dish" },
  { name: "SAPPORO", category: "DANIA", price_per_kg: 45.0, type: "dish" },
  { name: "NAGOJA", category: "DANIA", price_per_kg: 49.0, type: "dish" },
  { name: "WEGETARIAN SAN", category: "DANIA", price_per_kg: null, type: "dish" },
  { name: "SAN WEGAN", category: "DANIA", price_per_kg: null, type: "dish" },
  { name: "SAMON SAN", category: "DANIA", price_per_kg: null, type: "dish" },
  { name: "SENDAI", category: "DANIA", price_per_kg: null, type: "dish" },
  { name: "NARA", category: "DANIA", price_per_kg: null, type: "dish" },
]
