// Wbudowuje fonty Roboto (Regular + Bold) bezpośrednio w moduł TypeScript
// jako base64 data URI. To najpewniejsze rozwiązanie:
// - public/ NIE jest pakowane przez Next.js do lambdy serverless na Vercel
// - node_modules jest tracowane, ale @fontsource nie shipuje TTF w v5
// - fs.readFileSync przy runtime nie znajduje plików na lambdzie
//
// Rozwiązanie: czytamy TTF raz przy build, kodujemy base64, generujemy
// src/lib/sanepid/fonts-embedded.ts który eksportuje data URI.
// Next.js bundluje TS jak każdy inny moduł → font jedzie razem z JS.

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const SRC_DIR = path.join(ROOT, 'public', 'fonts')
const OUT_FILE = path.join(ROOT, 'src', 'lib', 'sanepid', 'fonts-embedded.ts')

const SOURCES = [
  { file: 'Roboto-Regular.ttf', name: 'robotoRegular' },
  { file: 'Roboto-Bold.ttf',    name: 'robotoBold'    },
]

function main() {
  // Weryfikuj obecność plików źródłowych
  const missing = SOURCES.filter(s => !fs.existsSync(path.join(SRC_DIR, s.file)))
  if (missing.length > 0) {
    console.error(`[fonts] BRAK plików TTF w public/fonts/: ${missing.map(m => m.file).join(', ')}`)
    console.error(`[fonts] Pobierz Roboto z https://fonts.google.com/specimen/Roboto i wrzuć Roboto-Regular.ttf + Roboto-Bold.ttf do public/fonts/`)

    // Wygeneruj pusty stub żeby TS się kompilował
    const stub = `// GENERATED STUB — fonty nie znalezione w public/fonts/\nexport const robotoRegular = ''\nexport const robotoBold = ''\n`
    fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
    fs.writeFileSync(OUT_FILE, stub)
    return
  }

  let content = `// AUTO-GENERATED by scripts/copy-fonts.js — do not edit manually.
// Fonty Roboto (latin-ext, obsługa polskich znaków) wbudowane jako base64
// żeby @react-pdf mógł je zarejestrować w serverless lambda na Vercel
// bez odczytu z dysku (public/ nie jest pakowane do lambdy).

`

  for (const s of SOURCES) {
    const buf = fs.readFileSync(path.join(SRC_DIR, s.file))
    const base64 = buf.toString('base64')
    const dataUri = `data:font/ttf;base64,${base64}`
    content += `export const ${s.name} = '${dataUri}'\n`
    console.log(`[fonts] ✓ ${s.file} → ${(buf.length / 1024).toFixed(1)} KB → ${s.name}`)
  }

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, content)
  console.log(`[fonts] Wygenerowano: ${path.relative(ROOT, OUT_FILE)}`)
}

try {
  main()
} catch (err) {
  console.error('[fonts] Błąd:', err.message)
  process.exit(1)
}
