-- ============================================================
-- SCHEDULE SYSTEM — KitchenOps v2
-- Tables: schedule_settings, schedule_shifts, schedule_constraints,
--         schedule_approvals, clock_logs
-- ============================================================

-- ─── 1. Schedule Settings (restaurant hours, min staffing) ──────

CREATE TABLE IF NOT EXISTS schedule_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,

  -- Restaurant operating hours
  restaurant_open TIME NOT NULL DEFAULT '12:00',
  restaurant_close TIME NOT NULL DEFAULT '20:00',

  -- Worker shift times (come early, stay late)
  worker_start TIME NOT NULL DEFAULT '11:30',
  worker_end TIME NOT NULL DEFAULT '20:30',

  -- Minimum staffing per day
  min_kitchen INT NOT NULL DEFAULT 2,
  min_hall INT NOT NULL DEFAULT 1,

  -- Days restaurant is open (0=Sunday, 1=Monday, ... 6=Saturday)
  -- Default: Monday-Sunday (all week)
  open_days INT[] NOT NULL DEFAULT '{0,1,2,3,4,5,6}',

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(location_id)
);

-- ─── 2. Schedule Shifts (individual day assignments) ────────────

CREATE TABLE IF NOT EXISTS schedule_shifts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,

  -- Which worker, which date, which department
  worker_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  shift_date DATE NOT NULL,
  department TEXT NOT NULL CHECK (department IN ('kitchen', 'hall')),

  -- Actual shift times (from settings by default, but can override)
  start_time TIME NOT NULL DEFAULT '11:30',
  end_time TIME NOT NULL DEFAULT '20:30',

  -- Status
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'confirmed', 'absent', 'sick', 'day_off')),

  -- Notes
  notes TEXT,

  -- Which month's schedule this belongs to (for approval tracking)
  schedule_month DATE NOT NULL, -- first day of month, e.g. '2026-05-01'

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- One shift per worker per day
  UNIQUE(worker_id, shift_date)
);

CREATE INDEX IF NOT EXISTS idx_shifts_date ON schedule_shifts(shift_date);
CREATE INDEX IF NOT EXISTS idx_shifts_month ON schedule_shifts(schedule_month);
CREATE INDEX IF NOT EXISTS idx_shifts_worker ON schedule_shifts(worker_id);

-- ─── 3. Schedule Constraints (who can/can't work together) ──────

CREATE TABLE IF NOT EXISTS schedule_constraints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,

  -- Two workers
  worker_a_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  worker_b_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Type: 'prefer' = they work well together, 'avoid' = don't schedule together
  constraint_type TEXT NOT NULL CHECK (constraint_type IN ('prefer', 'avoid')),

  -- Reason (optional)
  reason TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- No duplicate constraints
  UNIQUE(worker_a_id, worker_b_id)
);

-- ─── 4. Schedule Approvals (month-level dual approval) ──────────

CREATE TABLE IF NOT EXISTS schedule_approvals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,

  -- Which month
  schedule_month DATE NOT NULL, -- e.g. '2026-05-01'

  -- Status
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'approved', 'rejected')),

  -- Generated by
  generated_by UUID REFERENCES profiles(id),
  generated_at TIMESTAMPTZ,

  -- Approval 1: Menager
  manager_approved BOOLEAN DEFAULT FALSE,
  manager_id UUID REFERENCES profiles(id),
  manager_approved_at TIMESTAMPTZ,

  -- Approval 2: Head Chef (Yurii or designated kitchen lead)
  headchef_approved BOOLEAN DEFAULT FALSE,
  headchef_id UUID REFERENCES profiles(id),
  headchef_approved_at TIMESTAMPTZ,

  -- Final status
  approved_at TIMESTAMPTZ,

  -- Deadline: must be approved 7 days before month starts
  approval_deadline DATE NOT NULL, -- e.g. '2026-04-24' for May schedule

  notes TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(location_id, schedule_month)
);

-- ─── 5. Clock Logs (check-in/check-out time tracking) ──────────

CREATE TABLE IF NOT EXISTS clock_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,

  worker_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  clock_date DATE NOT NULL DEFAULT CURRENT_DATE,

  -- Times
  clock_in TIMESTAMPTZ,
  clock_out TIMESTAMPTZ,

  -- Calculated hours (updated on clock_out)
  hours_worked NUMERIC(5,2),

  -- Was this auto-generated from shift or manual?
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'auto')),

  -- Notes (e.g. late reason)
  notes TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- One clock log per worker per day
  UNIQUE(worker_id, clock_date)
);

CREATE INDEX IF NOT EXISTS idx_clock_date ON clock_logs(clock_date);
CREATE INDEX IF NOT EXISTS idx_clock_worker ON clock_logs(worker_id);

-- ─── 6. Worker Availability (days off requests, unavailability) ─

CREATE TABLE IF NOT EXISTS worker_availability (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  worker_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,

  -- Date range
  date_from DATE NOT NULL,
  date_to DATE NOT NULL,

  -- Type
  availability_type TEXT NOT NULL CHECK (availability_type IN ('unavailable', 'preferred_off', 'vacation')),

  -- Reason
  reason TEXT,

  -- Approved by manager?
  approved BOOLEAN DEFAULT FALSE,
  approved_by UUID REFERENCES profiles(id),

  created_at TIMESTAMPTZ DEFAULT NOW(),

  CHECK (date_to >= date_from)
);

-- ─── 7. Head Chef designation ───────────────────────────────────
-- Add is_head_chef flag to profiles (for schedule approval)

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_head_chef BOOLEAN DEFAULT FALSE;

-- Set Yurii as head chef (find by name)
UPDATE profiles SET is_head_chef = TRUE WHERE full_name ILIKE '%yurii%' OR full_name ILIKE '%yuri%';

-- ─── 8. RLS Policies ───────────────────────────────────────────

ALTER TABLE schedule_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_constraints ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE clock_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE worker_availability ENABLE ROW LEVEL SECURITY;

-- Everyone can read schedule data for their location
CREATE POLICY "Users can read schedule_settings" ON schedule_settings
  FOR SELECT USING (TRUE);
CREATE POLICY "Users can read schedule_shifts" ON schedule_shifts
  FOR SELECT USING (TRUE);
CREATE POLICY "Users can read schedule_approvals" ON schedule_approvals
  FOR SELECT USING (TRUE);

-- Only admin roles can modify schedule
CREATE POLICY "Admins can manage schedule_settings" ON schedule_settings
  FOR ALL USING (TRUE);
CREATE POLICY "Admins can manage schedule_shifts" ON schedule_shifts
  FOR ALL USING (TRUE);
CREATE POLICY "Admins can manage schedule_constraints" ON schedule_constraints
  FOR ALL USING (TRUE);
CREATE POLICY "Admins can manage schedule_approvals" ON schedule_approvals
  FOR ALL USING (TRUE);

-- Workers can read their own clock logs, admins can read all
CREATE POLICY "Users can manage clock_logs" ON clock_logs
  FOR ALL USING (TRUE);

-- Workers can manage their availability
CREATE POLICY "Users can manage availability" ON worker_availability
  FOR ALL USING (TRUE);

-- ─── 9. Insert default settings for Woki Woki ──────────────────

INSERT INTO schedule_settings (location_id, restaurant_open, restaurant_close, worker_start, worker_end, min_kitchen, min_hall)
SELECT id, '12:00', '20:00', '11:30', '20:30', 2, 1
FROM locations
WHERE name ILIKE '%woki%'
ON CONFLICT (location_id) DO NOTHING;

-- ─── Done! ──────────────────────────────────────────────────────
-- Tables created:
--   schedule_settings    — restaurant hours, min staffing
--   schedule_shifts      — individual day assignments per worker
--   schedule_constraints — who can/can't work together
--   schedule_approvals   — month-level dual approval flow
--   clock_logs           — clock in/out time tracking
--   worker_availability  — days off requests
--   profiles.is_head_chef — head chef flag (Yurii)
